### ISSUE TITLE
Where can I download your paper from ?

### ISSUE THREAD

**Issue by wyl010607** [guoshnBJTU/SSTBAN#1]
I can't found your paper _Self-Supervised Spatial-Temporal Bottleneck Attentive Network for Efficient Long-term Traffic Forecasting_ at IEEE or Google Scholar.

**Comment by guoshnBJTU** [comment]
> I can't found your paper _Self-Supervised Spatial-Temporal Bottleneck Attentive Network for Efficient Long-term Traffic Forecasting_ at IEEE or Google Scholar.

Hi, I have uploaded the paper.

**Comment by wyl010607** [comment]
thanks a lot
