### ISSUE TITLE
Inconsistency in the settings

### ISSUE THREAD

**Issue by xiaozheng7** [guoshnBJTU/SSTBAN#2]
Hi, Shengnan thanks for sharing the code and hope you are doing well. Just need some clarification on the setting of two hyper-parameters, 1) the number of attention heads and 2) the dimension of each attention head outputs. It seems that they are not consistent between the code and the paper (e.g., for PEMSD4_24, in the config file, K=16, d=8; while in TABLE III of the paper, h=8, d=16).

Can you please confirm which configuration is the right one?

**Comment by guoshnBJTU** [comment]
Hi, thank you for your question.
The symbols used to denote hyperparameters in our code are not consistent with the symbols used in our paper.  
In the paper, L, L', d, and h correspond to L, L, K, and d in the config file, respectively. 
According to this correspondence, the configurations in the config file are consistent with Table 3 in our paper.

**Comment by xiaozheng7** [comment]
> Hi, thank you for your question. The symbols used to denote hyperparameters in our code are not consistent with the symbols used in our paper. In the paper, L, L', d, and h correspond to L, L, K, and d in the config file, respectively. According to this correspondence, the configurations in the config file are consistent with Table 3 in our paper.

Ah I thought d and h in Table 3 represents the dimension of each attention head and no. of attention heads, respectively, according to the muilti-head attention equation above. It all makes sense now, thanks.
